version: '3.9'
services:
  frontend_profissional_site:
    container_name: site_prof_frontend
    build: ./frontend_profissional_site
    ports:
      - 8080:8080
    platform: linux/x86_64
    working_dir: /app/frontend_profissional_site
    # Os `healthcheck` devem garantir que a aplicação
    # está operacional, antes de liberar o container
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8080"]  # Caso utilize outra porta interna para o front, altere ela aqui também
      timeout: 10s
      retries: 5
    restart: 'always'
